import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import TopHeader from "./components/Layout/Header";
import Footer from "./components/Footer/Footer";
import { ConfigProvider, App as AntApp } from "antd";
import Providers from "./providers";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Two-Gooders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lato.variable}`}>
        <Providers>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: "var(--font-lato)",

                colorText: "#515151",
                colorTextBase: "#515151",
                colorTextHeading: "#515151",
                colorTextSecondary: "#515151",

                colorBg: "#FDFCF9",
                colorBgLayout: "#FDFCF9",
                colorBgContainer: "#FDFCF9",
              },

              components: {
                Typography: {
                  fontFamily: "var(--font-playfair)",
                  colorText: "#515151",
                },
                Table: {
                  borderRadius: 0,
                  headerBorderRadius: 0,
                },
                Menu: {
                  fontFamily: "var(--font-lato)",
                },
                Button: {
                  fontFamily: "var(--font-lato)",
                  borderRadius: 0,
                  colorText: "#515151",
                },
                Input: {
                  borderRadius: 0,
                  colorText: "#515151",
                },
                Select: {
                  borderRadius: 0,
                  colorText: "#515151",
                },
                Menu: {
                  fontFamily: "var(--font-lato)",
                  activeBarWidth: 0,
                  horizontalItemSelectedBg: "transparent",
                  horizontalItemSelectedColor: "#000",
                  horizontalItemHoverColor: "#000",
                  activeBarHeight: 3,
                },
              },
            }}
          >
            <TopHeader />
            <AntApp>
            <main>{children}</main>
            </AntApp>
            <Footer />
          </ConfigProvider>
        </Providers>
      </body>
    </html>
  );
}
